
name: pytorch_video2

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python==3.8.3
  - pip==21.3.1
  - cudatoolkit=10.1
  - libgcc-ng
  - libstdcxx-ng
  - matplotlib==3.5.1
  - pip:
      - GitPython==3.1.2
      - jupyter==1.0.0
      - ffmpeg-python==0.2.0
      - imageio==2.13.5
      - matplotlib
      - moviepy
      - numpy
      - pandas
      - Pillow
      - requests
      - scikit-learn
      - scikit-video
      - scipy
      - tensorboard
      - tensorboardX
      - torch==1.10.0+cu113
      - torchvision
      - tqdm
      - imageio-ffmpeg
      - ffmpeg
      - sk-video
      - kornia
