
name: pytorch_video

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python==3.8.3
  - pip==20.0.2
  - cudatoolkit=10.1
  - libgcc-ng
  - libstdcxx-ng
  - pytorch==1.5.0
  - torchtext==0.6.0
  - matplotlib==3.1.3
  - pip:
      - GitPython==3.1.2
      - jupyter==1.0.0
      - ffmpeg-python==0.1.17
      - imageio==2.4.1
      - matplotlib==3.0.3
      - moviepy==0.2.3.5
      - numpy==1.15.4
      - pandas==0.23.4
      - Pillow==6.0.0
      - requests==2.21.0
      - scikit-learn==0.20.1
      - scikit-video==1.1.11
      - scipy==1.2.1
      - tensorboard==1.14.0
      - tensorboardX==1.4
      - torch==0.4.1
      - torchvision==0.2.1
      - tqdm==4.31.1
